version: '3'

networks:
   db-net:
     external:
         name: docker-compose_db-net
   proxy:
     external:
         name: docker-compose_proxy

services:
   kibana:
     image: docker.elastic.co/kibana/kibana:7.6.0
     container_name: admin-${ID}-kibana
     volumes:
       - ../Slave/Admin/services/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
     networks:
       - db-net
       - proxy

   phpmyadmin:
     image: phpmyadmin/phpmyadmin
     container_name: admin-${ID}-phpmyadmin
     environment:
       - PMA_ARBITRARY=1
     restart: always
     volumes:
       - ../Slave/Admin/services/phpmyadmin/sessions:/sessions
       - ../Slave/Admin/services/phpmyadmin/config.inc.php:/etc/phpmyadmin/config.inc.php:ro
     external_links:
       - datab:db
     networks:
       - db-net
       - proxy
     environment:
       PMA_USER: ${DB_USER}
       PMA_PASSWORD: ${DB_PASS}

   php:
      image: php:fpm-alpine
      container_name: admin-${ID}-php
      volumes:
        - ../Slave/Admin/front:/script:ro
      networks:
        - proxy
      environment:
        HOST: admin.${ID}.${SMARTDOM_DOMAIN}

   admin:
      image: nginx
      container_name: admin-${ID}-web
      restart: always
      volumes:
        - ../Wellcheck/Admin/front:/usr/share/nginx/html:ro
        - ../Wellcheck/Admin/conf/admin.conf:/etc/nginx/conf.d/default.conf:ro
      links:
        - phpmyadmin
        - kibana
        - php2
      networks:
        - proxy
      environment:
        VIRTUAL_HOST: admin.${ID}.${DOMAIN}
        VIRTUAL_PORT: 80
        LETSENCRYPT_HOST: admin.${ID}.${DOMAIN}
        LETSENCRYPT_EMAIL: ${EMAIL}
