version: '3'

networks:
   proxy:
     external:
       name: smart_proxy
   adm-net:
     external:
         name: smart_smartdom-adm-net
   db-net:
     external:
         name: smart_smartdom-db-net

services:
   smartdom-admin-kibana:
     image: docker.elastic.co/kibana/kibana:7.6.0
     container_name: smartdom-admin-kibana
     volumes:
       - ./Smartdom/Admin/services/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
     networks:
       - db-net
       - adm-net

   smartdom-admin-kanboard:
     image: kanboard/kanboard:latest
     container_name: smartdom-admin-kanboard
     volumes:
       - ./Smartdom/Admin/services/kanboard/conf/config.php:/var/www/app/config.php
       - ./Smartdom/Admin/services/kanboard/data:/var/www/app/data
       - ./Smartdom/Admin/services/kanboard/plugins:/var/www/app/plugins
     networks:
       - adm-net

   smartdom-admin-phpmyadmin:
     image: phpmyadmin/phpmyadmin
     container_name: smartdom-admin-phpmyadmin
     environment:
       - PMA_ARBITRARY=1
     restart: always
     volumes:
       - ./Smartdom/Admin/services/phpmyadmin/sessions:/sessions
       - ./Smartdom/Admin/services/phpmyadmin/config.inc.php:/etc/phpmyadmin/config.inc.php:ro
     external_links:
       - smartdom-web-sql:db
     networks:
       - db-net
       - adm-net
     environment:
       PMA_USER: ${SMARTDOM_DB_USER}
       PMA_PASSWORD: ${SMARTDOM_DB_PASS}

   smartdom-admin-postmanviewer:
      build: ./Smartdom/Admin/services/postman-collection-viewer/
      container_name: smartdom-admin-postmanviewer
      restart: always
      tty: true
      stdin_open: true
      expose:
       - 80
      networks:
        - adm-net

   smartdom-admin-goaccess:
     image: nginx
     container_name: smartdom-admin-goaccess
     restart: always
     volumes:
       - ./Smartdom/Admin/services/goaccess/front:/usr/share/nginx/html:ro
     networks:
       - adm-net

   smartdom-admin-goaccesscli:
     image: allinurl/goaccess
     container_name: smartdom-admin-goaccesscli
     volumes:
       - ./Proxy/logs/services:/logs/:ro
       - ./Smartdom/Admin/services/goaccess/conf:/etc/goaccess/
       - ./Smartdom/Admin/services/front:/results/
     entrypoint: "watch `goaccess /logs/${SMARTDOM_DOMAIN}.log -o /results/${SMARTDOM_DOMAIN}.html --log-format=COMBINED;
                        goaccess /logs/dashboard.${SMARTDOM_DOMAIN}.log -o /results/dashboard${SMARTDOM_DOMAIN}.html --log-format=COMBINED;
                        goaccess /logs/api.${SMARTDOM_DOMAIN}.log -o /results/api${SMARTDOM_DOMAIN}.html --log-format=COMBINED;`
                "

   smartdom-admin-php:
     image: php:fpm-alpine
     container_name: smartdom-admin-php
     volumes:
       - ./Smartdom/Admin/front:/script:ro
       - ./Smartdom/Admin/services/goaccess/front:/stats:ro
     networks:
       - adm-net
     environment:
       HOST: ${SMARTDOM_DOMAIN}

   smartdom-admin-nginx:
     image: nginx
     container_name: smartdom-admin-nginx
     restart: always
     volumes:
       - ./Smartdom/Admin/front:/usr/share/nginx/html:ro
       - ./Smartdom/Admin/conf/admin.conf:/etc/nginx/conf.d/default.conf:ro
     links:
       - smartdom-admin-goaccess
       - smartdom-admin-phpmyadmin
       - smartdom-admin-kibana
       - smartdom-admin-php
       - smartdom-admin-kanboard
     networks:
       - proxy
       - adm-net
     environment:
       VIRTUAL_HOST: admin.${SMARTDOM_DOMAIN}
       VIRTUAL_PORT: 80
       LETSENCRYPT_HOST: admin.${SMARTDOM_DOMAIN}
       LETSENCRYPT_EMAIL: ${SMARTDOM_EMAIL}
