version: '3'

networks:
    proxy:
      external:
        name: docker-compose_proxy
    db-net-{{ID}}:
      internal: true

services:

  db-{{ID}}:
    container_name: wordpress-{{ID}}-db
    image: mariadb:latest
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - db-net-{{ID}}
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: $V_DB_NAME
      MYSQL_USER: $V_DB_USER
      MYSQL_PASSWORD: $V_DB_PASSWORD
    healthcheck:
      test: "/usr/bin/mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 30s
      timeout: 3s
      retries: 2

  wp-{{ID}}:
    container_name: wordpress-{{ID}}-web
    build: .
    depends_on:
      - db-{{ID}}
    restart: always
    volumes:
      - ./html:/var/www/html:rw
      - ./.htaccess:/var/www/html:ro
    networks:
      - proxy
      - db-net-{{ID}}
    environment:
      WORDPRESS_DB_HOST: db-{{ID}}
      WORDPRESS_DB_NAME: $V_DB_NAME
      WORDPRESS_DB_USER: $V_DB_USER
      WORDPRESS_DB_PASSWORD: $V_DB_PASSWORD
      WORDPRESS_TABLE_PREFIX: $V_WP_TABLE_PREFIX
      VIRTUAL_HOST: $V_VIRTUAL_HOST
      VIRTUAL_PORT: $V_VIRTUAL_PORT
      LETSENCRYPT_HOST: $V_VIRTUAL_HOST
      LETSENCRYPT_EMAIL: $V_LETSENCRYPT_EMAIL
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:$$VIRTUAL_PORT"]
      interval: 30s
      timeout: 3s
      retries: 5
