version: "3"

services:
  build-dashboard:
    build: .
    container_name: build-dashboard
    volumes:
      - ../../Smartco/Webapps/dashboard.smartco:/app/

  build-ged:
    build: .
    container_name: build-ged
    volumes:
      - ../../Smartco/Webapps/ged.smartco:/app/

  build-ged-brainy:
    build: .
    container_name: build-ged-brainy
    volumes:
      - ../../Smartco/Webapps/ged.brainyfood:/app/

  build-ged-brainy:
    build: .
    container_name: build-ged-brainy
    volumes:
      - ../../Smartco/Webapps/ged.enfin:/app/
