version: "3"

services:
  build-assembly:
    build: .
    container_name: build-assembly
    volumes:
      - ../../Smartdom/Webapps/assemblee.smartdom:/app/

  build-quinsac:
    build: .
    container_name: build-quinsac
    volumes:
      - ../../Smartdom/Webapps/quinsac.smartdom:/app/

  build-smartdom:
    build: .
    container_name: build-smartdom
    volumes:
      - ../../Smartdom/Webapps/smartdom:/app/

  build-veloone:
    build: .
    container_name: build-veloone
    volumes:
      - ../../Smartdom/Webapps/veloone.smartdom:/app/

  build-dark:
    build: .
    container_name: build-dark
    volumes:
      - ../../Smartdom/Webapps/ged/ged.dark_kitchen:/app/
