version: '3'

networks:
  proxy:
    external:
      name: docker-compose_proxy
  web-net:
    external:
      name: docker-compose_smartdom-web-net
  db-net:
    external:
      name: docker-compose_smartdom-db-net

services:
  smartdom-web-sql:
    image: mysql:5.7
    container_name: smartdom-web-sql
    restart: always
    networks:
      - db-net
    volumes:
      - ../Smartdom/Micro/sql/data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: ${SMARTDOM_DB_USER}
      MYSQL_DATABASE: smartdom
      MYSQL_PASSWORD: ${SMARTDOM_DB_PASS}

  smartdom-web-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: smartdom-web-elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=false
      - cluster.routing.allocation.disk.threshold_enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ../Smartdom/Micro/elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - db-net

  map_bck-end:
    build: ../Smartdom/Webapps/api.smartdom
    expose:
      - 8080
    tty: true
    stdin_open: true
    depends_on:
      - smartdom-web-sql
    networks:
      - db-net
      - proxy
    volumes:
      - ../Smartdom/Webapps/api.smartdom:/home/api/
    environment:
      VIRTUAL_HOST: api.${SMARTDOM_DOMAIN}
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: api.${SMARTDOM_DOMAIN}
      LETSENCRYPT_EMAIL: ${SMARTDOM_EMAIL}
      API_MOD: ${SMARTDOM_API_MOD}
      API_PASS: password
      API_ADM: ${SMARTDOM_API_ADM}
      DB_USER: ${SMARTDOM_DB_USER}
      DB_PASS: ${SMARTDOM_DB_PASS}
      STRIPE_PRIV: ${SMARTDOM_STRIPE_PRIV}
      WEB3_INFURA_PROJECT_ID: ${WEB3_INFURA_PROJECT_ID}
      WEB3_INFURA_API_KEY: ${WEB3_INFURA_PROJECT_ID}
      ETH_ADM_MNEMONIC: ${SMARTDOM_ETH_ADM_MNEMONIC}

  smartdom-veloone:
     build: ../Smartdom/Webapps/veloone.smartdom/
     container_name: smartdom-veloone-nginx
     restart: always
     tty: true
     stdin_open: true
     expose:
      - 5000
     networks:
       - proxy
     environment:
       VIRTUAL_HOST: veloone.${SMARTDOM_DOMAIN}
       VIRTUAL_PORT: 5000
       LETSENCRYPT_HOST: veloone.${SMARTDOM_DOMAIN}
       LETSENCRYPT_EMAIL: ${SMARTDOM_EMAIL}

  smartdom-quinsac:
     build: ../Smartdom/Webapps/quinsac.smartdom/
     container_name: smartdom-quinsac-nginx
     restart: always
     tty: true
     stdin_open: true
     expose:
      - 5000
     networks:
       - proxy
     environment:
       VIRTUAL_HOST: quinsac.${SMARTDOM_DOMAIN}
       VIRTUAL_PORT: 5000
       LETSENCRYPT_HOST: quinsac.${SMARTDOM_DOMAIN}
       LETSENCRYPT_EMAIL: ${SMARTDOM_EMAIL}

  smartdom-assemblee:
     build: ../Smartdom/Webapps/assemblee.smartdom/
     container_name: smartdom-assemblee-nginx
     restart: always
     tty: true
     stdin_open: true
     expose:
      - 5000
     networks:
       - proxy
     environment:
       VIRTUAL_HOST: assemblee.${SMARTDOM_DOMAIN}
       VIRTUAL_PORT: 5000
       LETSENCRYPT_HOST: assemblee.${SMARTDOM_DOMAIN}
       LETSENCRYPT_EMAIL: ${SMARTDOM_EMAIL}

  smartdom-web:
     build: ../Smartdom/Webapps/smartdom/
     container_name: smartdom-web-yarn
     restart: always
     tty: true
     stdin_open: true
     expose:
      - 5000
     networks:
       - proxy
     environment:
       VIRTUAL_HOST: ${SMARTDOM_DOMAIN}
       VIRTUAL_PORT: 5000
       LETSENCRYPT_HOST: ex.${SMARTDOM_DOMAIN}
       LETSENCRYPT_EMAIL: ex.${SMARTDOM_EMAIL}
