version: '3'

networks:
  proxy:
    external:
      name: docker-compose_proxy
  web-net:
    external:
      name: docker-compose_smartco-web-net
  db-net:
    external:
      name: docker-compose_smartco-db-net

services:
  smartco-web-sql:
    image: mysql:5.7
    container_name: smartco-web-sql
    restart: always
    networks:
      - db-net
    volumes:
      - ../Smartco/Micro/sql/data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: ${SMARTCO_DB_USER}
      MYSQL_DATABASE: smartco
      MYSQL_PASSWORD: ${SMARTCO_DB_PASS}

  smartco-web-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: smartco-web-elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=false
      - cluster.routing.allocation.disk.threshold_enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ../Smartco/Micro/elasticsearch/data:/usr/share/elasticsearch/data
      - ../Smartco/Micro/elasticsearch/conf.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    networks:
      - db-net

  map_bck-end:
    build: ../Smartco/Webapps/api.smartco
    ports:
      - 8080:8080
    tty: true
    stdin_open: true
    depends_on:
      - smartco-web-sql
    networks:
      - db-net
      - proxy
    volumes:
      - ../Smartco/Webapps/api.smartco:/home/api/
      - ../Smartco/Webapps/doc.smartco:/home/ged/
    environment:
      VIRTUAL_HOST: api.${SMARTCO_DOMAIN}
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: api.${SMARTCO_DOMAIN}
      LETSENCRYPT_EMAIL: ${SMARTCO_EMAIL}
      API_MOD: ${SMARTCO_API_MOD}
      API_PASS: 1q2W3e4R%T^Y
      API_ADM: ${SMARTCO_API_ADM}
      DB_USER: ${SMARTCO_DB_USER}
      DB_PASS: ${SMARTCO_DB_PASS}
      STRIPE_PRIV: ${SMARTCO_STRIPE_PRIV}
      WEB3_INFURA_PROJECT_ID: ${WEB3_INFURA_PROJECT_ID}
      WEB3_INFURA_API_KEY: ${WEB3_INFURA_PROJECT_ID}
      ETH_ADM_MNEMONIC: ${SMARTCO_ETH_ADM_MNEMONIC}

  db-smartco:
    container_name: smartco-wp-sql
    image: mariadb:latest
    restart: always
    volumes:
      - ../Smartco/Micro/sqlwp/data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: ${SMARTCO_DB_USER}
      MYSQL_DATABASE: smartco
      MYSQL_PASSWORD: ${SMARTCO_DB_PASS}
    networks:
      - db-net

  wp-smartco:
    container_name: smartco-wp-web
    build: ../Smartco/Webapps/wp.smartco/
    depends_on:
      - db-smartco
    restart: always
    volumes:
      - ../Smartco/Webapps/wp.smartco/html:/var/www/html:rw
    environment:
      WORDPRESS_DB_HOST: smartco-wp-sql
      WORDPRESS_DB_NAME: smartco
      WORDPRESS_DB_USER: ${SMARTCO_DB_USER}
      WORDPRESS_DB_PASSWORD: ${SMARTCO_DB_PASS}
      WORDPRESS_TABLE_PREFIX: wp
      VIRTUAL_HOST: ${SMARTCO_DOMAIN}
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: ${SMARTCO_DOMAIN}
      LETSENCRYPT_EMAIL: ${SMARTCO_EMAIL}
    networks:
      - db-net
      - proxy
