version: "3"

networks:
    proxy:
      driver: bridge
    smartco-db-net:
      internal: true
    smartco-web-net:
      internal: true
    smartco-adm-net:
      internal: true
    smartdom-db-net:
      internal: true
    smartdom-web-net:
      internal: true
    smartdom-adm-net:
      internal: true

services:
    nginx:
        image: jwilder/nginx-proxy:alpine
        container_name: nginx
        restart: always
        labels:
            com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: 'true'
        ports:
            - 80:80
            - 443:443
        volumes:
            - ../Proxy/conf/proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
            - ../Proxy/logs/global:/var/log/nginx
            - ../Proxy/vhost:/etc/nginx/vhost.d
            - ../Proxy/passwd:/etc/nginx/htpasswd
            - ../Proxy/data/html:/usr/share/nginx/html
            - ../Proxy/data/certs:/etc/nginx/certs:ro
            - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
            - proxy

    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: letsencrypt
        volumes:
            - ../Proxy/vhost:/etc/nginx/vhost.d
            - ../Proxy/data/html:/usr/share/nginx/html
            - ../Proxy/data/certs:/etc/nginx/certs:rw
            - /var/run/docker.sock:/var/run/docker.sock:ro
        depends_on:
            - nginx
        networks:
            - proxy
            - smartco-db-net
            - smartco-web-net
            - smartco-adm-net
            - smartdom-db-net
            - smartdom-web-net
            - smartdom-adm-net
