version: "3"

networks:
    proxy:
      external:
        name: docker-compose_proxy

services:
    posteio:
        image: analogic/poste.io
        restart: always
        ports:
            - 0.0.0.0:25:25
            - 110:110
            - 143:143
            - 465:465
            - 587:587
            - 993:993
            - 995:995
            - 4190:4190
        expose:
            - 80
        volumes:
            - ../Smartdom/Micro/posteio:/data
        environment:
            TZ: Europe/Prague
            HTTPS: 'OFF'
            VIRTUAL_HOST: mail.${ROCKET_DOMAIN},mail.${SMARTDOM_DOMAIN}
            VIRTUAL_PORT: 80
            LETSENCRYPT_HOST: mail.${ROCKET_DOMAIN},mail.${SMARTDOM_DOMAIN}
            LETSENCRYPT_EMAIL: ${SMARTDOM_EMAIL}
            DISABLE_CLAMAV: TRUE
            DISABLE_RSPAMD: TRUE
            HTTPS: OFF
        networks:
            - proxy
